import { ThirdPartyFormIntegration, IntegrationLogItem } from './types';

export const initialThirdPartyIntegrations: ThirdPartyFormIntegration[] = [
  {
    id: 'integ-sap-po',
    name: 'SAP S/4HANA 采购订单与大额付款审批接入',
    code: 'SAP_PO_PAYMENT_V1',
    systemType: 'ERP',
    systemName: 'SAP S/4HANA',
    systemIconBg: 'bg-blue-600',
    protocol: 'webhook',
    endpoint: 'https://api.formcraft.internal/v1/thirdparty/sap-po/webhook',
    appKey: 'fc_app_sap_987a6c52',
    appSecret: 'sec_7b89d4128f90c34e81a329e47265a109',
    status: 'active',
    targetFormId: 'f2',
    targetFormName: '采购付款审批单',
    targetWorkflowName: '多级财务与预算会签流',
    description: '当 SAP ERP 系统生成状态为“待批准”的采购订单时，通过 Webhook 实时上报表单并触发本平台多级财务合规审批流程。',
    fieldMappings: [
      { id: 'm1', sourceField: 'po_number', sourceLabel: '采购凭证号', sourceType: 'string', targetFieldId: 'field_po', targetFieldLabel: '采购订单单号', isRequired: true, transformRule: 'direct' },
      { id: 'm2', sourceField: 'vendor_name', sourceLabel: '供应商名称', sourceType: 'string', targetFieldId: 'field_vendor', targetFieldLabel: '收款单位', isRequired: true, transformRule: 'direct' },
      { id: 'm3', sourceField: 'net_price_cent', sourceLabel: '订单净额(分)', sourceType: 'number', targetFieldId: 'field_amount', targetFieldLabel: '付款金额(元)', isRequired: true, transformRule: 'cent_to_yuan' },
      { id: 'm4', sourceField: 'purchasing_group', sourceLabel: '采购组编码', sourceType: 'string', targetFieldId: 'field_dept', targetFieldLabel: '申请部门', isRequired: true, transformRule: 'direct' },
      { id: 'm5', sourceField: 'creator_mail', sourceLabel: '创建人工号/邮箱', sourceType: 'string', targetFieldId: 'field_applicant', targetFieldLabel: '申请人', isRequired: true, transformRule: 'direct' },
      { id: 'm6', sourceField: 'document_date', sourceLabel: '单据日期', sourceType: 'date', targetFieldId: 'field_date', targetFieldLabel: '预计使用日期', isRequired: false, transformRule: 'timestamp_to_date' },
    ],
    callbackConfig: {
      onApprovedUrl: 'https://erp.enterprise-cloud.cn/bapi/po/release-approve',
      onRejectedUrl: 'https://erp.enterprise-cloud.cn/bapi/po/release-reject',
      callbackAuthType: 'bearer',
      callbackToken: 'sap_bearer_token_sec_99381',
      retryCount: 3,
      timeoutSec: 10,
    },
    stats: {
      totalCalls: 3420,
      successCalls: 3418,
      failedCalls: 2,
      lastTriggerTime: '10分钟前',
      avgDurationMs: 320,
    },
    createdAt: '2026-03-15',
    updatedAt: '2026-09-22',
  },
  {
    id: 'integ-fx-crm',
    name: '纷享销客 CRM - 重点商机特批商务折扣申请',
    code: 'CRM_OPP_DISCOUNT_TRIGGER',
    systemType: 'CRM',
    systemName: '纷享销客 CRM',
    systemIconBg: 'bg-emerald-600',
    protocol: 'sdk_openapi',
    endpoint: 'https://api.formcraft.internal/v1/thirdparty/crm-discount/openapi',
    appKey: 'fc_app_crm_e52109ab',
    appSecret: 'sec_8192a0937f28bc91d24301fae8125432',
    status: 'active',
    targetFormId: 'f1',
    targetFormName: '特批商务折扣申请',
    targetWorkflowName: '大客户商业折扣委员会特批流',
    description: '销售人员在 CRM 中针对特惠大单申请破底折扣时，自动接入表单并唤起风控总监与业务VP在线决策协同。',
    fieldMappings: [
      { id: 'm21', sourceField: 'opportunity_id', sourceLabel: '商机编号', sourceType: 'string', targetFieldId: 'field_opp', targetFieldLabel: '商机编号', isRequired: true, transformRule: 'direct' },
      { id: 'm22', sourceField: 'customer_name', sourceLabel: '客户企业全称', sourceType: 'string', targetFieldId: 'field_customer', targetFieldLabel: '大客户名称', isRequired: true, transformRule: 'direct' },
      { id: 'm23', sourceField: 'contract_total_amount', sourceLabel: '预计签约总价(元)', sourceType: 'number', targetFieldId: 'field_contract_val', targetFieldLabel: '合同金额', isRequired: true, transformRule: 'direct' },
      { id: 'm24', sourceField: 'proposed_discount', sourceLabel: '申请折扣率(如0.82)', sourceType: 'number', targetFieldId: 'field_discount', targetFieldLabel: '特批折扣', isRequired: true, transformRule: 'direct' },
      { id: 'm25', sourceField: 'sales_rep_name', sourceLabel: '销售代表姓名', sourceType: 'string', targetFieldId: 'field_rep', targetFieldLabel: '申报销售', isRequired: true, transformRule: 'direct' },
    ],
    callbackConfig: {
      onApprovedUrl: 'https://crm.fxiaoke.com/openapi/v2/opportunity/discount-sync',
      onRejectedUrl: 'https://crm.fxiaoke.com/openapi/v2/opportunity/discount-sync',
      callbackAuthType: 'bearer',
      callbackToken: 'crm_fx_api_token_k91823',
      retryCount: 3,
      timeoutSec: 8,
    },
    stats: {
      totalCalls: 1890,
      successCalls: 1890,
      failedCalls: 0,
      lastTriggerTime: '1小时前',
      avgDurationMs: 245,
    },
    createdAt: '2026-04-02',
    updatedAt: '2026-09-23',
  },
  {
    id: 'integ-feishu-hr',
    name: '飞书人事 People - 员工假勤异常打卡补签接入',
    code: 'FEISHU_ATTENDANCE_OVERRIDE',
    systemType: 'HRM',
    systemName: '飞书 (Feishu/Lark)',
    systemIconBg: 'bg-indigo-600',
    protocol: 'webhook',
    endpoint: 'https://api.formcraft.internal/v1/thirdparty/feishu-attendance/webhook',
    appKey: 'fc_app_feishu_d7328109',
    appSecret: 'sec_feishu_992147acb81023719b4802c610992381',
    status: 'active',
    targetFormId: 'f3',
    targetFormName: '异常考勤申报表',
    targetWorkflowName: '直属领导与考勤组审批流',
    description: '订阅飞书开放平台打卡异常事件，员工于移动端提交异常原因后自动流转至本平台，审批终审结果自动写回飞书考勤组。',
    fieldMappings: [
      { id: 'm31', sourceField: 'employee_open_id', sourceLabel: '飞书人员OpenID', sourceType: 'string', targetFieldId: 'field_emp_id', targetFieldLabel: '员工工号', isRequired: true, transformRule: 'direct' },
      { id: 'm32', sourceField: 'employee_name', sourceLabel: '员工花名/姓名', sourceType: 'string', targetFieldId: 'field_name', targetFieldLabel: '申报人员', isRequired: true, transformRule: 'direct' },
      { id: 'm33', sourceField: 'abnormal_date', sourceLabel: '打卡异常发生日期', sourceType: 'date', targetFieldId: 'field_date', targetFieldLabel: '异常考勤日期', isRequired: true, transformRule: 'direct' },
      { id: 'm34', sourceField: 'exception_reason', sourceLabel: '补卡原由说明', sourceType: 'string', targetFieldId: 'field_reason', targetFieldLabel: '假勤异常说明', isRequired: true, transformRule: 'direct' },
      { id: 'm35', sourceField: 'attachment_url', sourceLabel: '凭证截图URL', sourceType: 'string', targetFieldId: 'field_proof', targetFieldLabel: '佐证材料', isRequired: false, transformRule: 'direct' },
    ],
    callbackConfig: {
      onApprovedUrl: 'https://open.feishu.cn/open-apis/attendance/v1/user_approvals/sync',
      onRejectedUrl: 'https://open.feishu.cn/open-apis/attendance/v1/user_approvals/sync',
      callbackAuthType: 'bearer',
      callbackToken: 't-g1049c8192FeiShuTenantToken',
      retryCount: 5,
      timeoutSec: 15,
    },
    stats: {
      totalCalls: 5610,
      successCalls: 5596,
      failedCalls: 14,
      lastTriggerTime: '25分钟前',
      avgDurationMs: 180,
    },
    createdAt: '2026-03-20',
    updatedAt: '2026-09-23',
  },
  {
    id: 'integ-mall-refund',
    name: '自研电商中台 - 售后大额退款特批表单接入',
    code: 'MICRO_ORDER_HIGH_REFUND',
    systemType: 'CUSTOM',
    systemName: '自研业务中台微服务',
    systemIconBg: 'bg-rose-600',
    protocol: 'rest_api',
    endpoint: 'https://api.formcraft.internal/v1/thirdparty/custom-refund/submit',
    appKey: 'fc_app_mall_a3399021',
    appSecret: 'sec_mall_59281a8b92019c4d9283749001ab4399',
    status: 'active',
    targetFormId: 'f4',
    targetFormName: '差旅预支申请单',
    targetWorkflowName: '退款风控专员与总监联审',
    description: '当 C 端用户在商城申请单笔超过 5,000 元的售后退款时，由交易中台自动通过 RESTful API 推送表单，终审通过后自动唤起微信/支付宝原路退汇。',
    fieldMappings: [
      { id: 'm41', sourceField: 'refund_sn', sourceLabel: '退款申请流水号', sourceType: 'string', targetFieldId: 'field_sn', targetFieldLabel: '退款单号', isRequired: true, transformRule: 'direct' },
      { id: 'm42', sourceField: 'order_sn', sourceLabel: '原始订单号', sourceType: 'string', targetFieldId: 'field_order', targetFieldLabel: '关联合同订单', isRequired: true, transformRule: 'direct' },
      { id: 'm43', sourceField: 'refund_fee_yuan', sourceLabel: '申请退款金额', sourceType: 'number', targetFieldId: 'field_fee', targetFieldLabel: '涉及金额', isRequired: true, transformRule: 'direct' },
      { id: 'm44', sourceField: 'user_uid', sourceLabel: '客户会员ID', sourceType: 'string', targetFieldId: 'field_uid', targetFieldLabel: '申领人', isRequired: true, transformRule: 'direct' },
    ],
    callbackConfig: {
      onApprovedUrl: 'https://trade-api.internal-mall.com/order/refund/action-approve',
      onRejectedUrl: 'https://trade-api.internal-mall.com/order/refund/action-reject',
      callbackAuthType: 'custom_header',
      callbackToken: 'X-Mall-Service-Secret-8841',
      retryCount: 3,
      timeoutSec: 10,
    },
    stats: {
      totalCalls: 2150,
      successCalls: 2142,
      failedCalls: 8,
      lastTriggerTime: '3小时前',
      avgDurationMs: 290,
    },
    createdAt: '2026-05-10',
    updatedAt: '2026-09-21',
  },
  {
    id: 'integ-yonsuite-asset',
    name: '用友 YonSuite - 固定资产跨部门调拨申请',
    code: 'YONSUITE_ASSET_TRANSFER',
    systemType: 'ERP',
    systemName: '用友 YonSuite',
    systemIconBg: 'bg-amber-600',
    protocol: 'rest_api',
    endpoint: 'https://api.formcraft.internal/v1/thirdparty/yonsuite-asset/webhook',
    appKey: 'fc_app_yonsuite_b1093847',
    appSecret: 'sec_yon_301948ba290184c7e81923019842bc19',
    status: 'testing',
    targetFormId: 'f5',
    targetFormName: 'IT资产申领单',
    targetWorkflowName: '资产管理部与接收部门交接流',
    description: '接入用友 YonSuite 资产云模块，针对服务器、高阶精密仪器在分公司/跨部门间的调拨借调进行数字表单审批与卡片台账联动更新。',
    fieldMappings: [
      { id: 'm51', sourceField: 'asset_card_id', sourceLabel: '资产卡片编号', sourceType: 'string', targetFieldId: 'field_asset_id', targetFieldLabel: '资产编号', isRequired: true, transformRule: 'direct' },
      { id: 'm52', sourceField: 'asset_title', sourceLabel: '资产名称型号', sourceType: 'string', targetFieldId: 'field_asset_name', targetFieldLabel: '设备名称', isRequired: true, transformRule: 'direct' },
      { id: 'm53', sourceField: 'from_org_code', sourceLabel: '原归属部门', sourceType: 'string', targetFieldId: 'field_from_org', targetFieldLabel: '调出部门', isRequired: true, transformRule: 'direct' },
      { id: 'm54', sourceField: 'to_org_code', sourceLabel: '接收目的部门', sourceType: 'string', targetFieldId: 'field_to_org', targetFieldLabel: '调入部门', isRequired: true, transformRule: 'direct' },
    ],
    callbackConfig: {
      onApprovedUrl: 'https://api.diwork.com/asset/v1/card/transfer/confirm',
      onRejectedUrl: 'https://api.diwork.com/asset/v1/card/transfer/cancel',
      callbackAuthType: 'bearer',
      callbackToken: 'yon_open_token_19283912',
      retryCount: 3,
      timeoutSec: 10,
    },
    stats: {
      totalCalls: 410,
      successCalls: 404,
      failedCalls: 6,
      lastTriggerTime: '昨天 14:20',
      avgDurationMs: 410,
    },
    createdAt: '2026-06-18',
    updatedAt: '2026-09-20',
  },
  {
    id: 'integ-beisen-hr',
    name: '北森 HRM - 核心管理干部晋升与录用特批',
    code: 'BEISEN_OFFER_SPECIAL_APPROVAL',
    systemType: 'HRM',
    systemName: '北森 Beisen 云',
    systemIconBg: 'bg-cyan-600',
    protocol: 'webhook',
    endpoint: 'https://api.formcraft.internal/v1/thirdparty/beisen-offer/webhook',
    appKey: 'fc_app_beisen_c8192348',
    appSecret: 'sec_beisen_9918204cba7192837491028374619283',
    status: 'active',
    targetFormId: 'f6',
    targetFormName: '员工录用审批表',
    targetWorkflowName: '总经办与薪酬委员会定薪流',
    description: '接入北森招聘系统，当候选人定薪超出职级带宽或含有高阶股权激励方案时，自动触发跨级特批表单。',
    fieldMappings: [
      { id: 'm61', sourceField: 'candidate_id', sourceLabel: '候选人档案ID', sourceType: 'string', targetFieldId: 'field_cand_id', targetFieldLabel: '拟录用人员ID', isRequired: true, transformRule: 'direct' },
      { id: 'm62', sourceField: 'candidate_name', sourceLabel: '候选人姓名', sourceType: 'string', targetFieldId: 'field_cand_name', targetFieldLabel: '拟录用人员', isRequired: true, transformRule: 'direct' },
      { id: 'm63', sourceField: 'target_level', sourceLabel: '定岗定级', sourceType: 'string', targetFieldId: 'field_level', targetFieldLabel: '定岗职级', isRequired: true, transformRule: 'direct' },
      { id: 'm64', sourceField: 'monthly_salary', sourceLabel: '月薪标准(元)', sourceType: 'number', targetFieldId: 'field_salary', targetFieldLabel: '核准薪资', isRequired: true, transformRule: 'direct' },
    ],
    callbackConfig: {
      onApprovedUrl: 'https://openapi.beisen.com/v2/recruitment/offer/approve-notify',
      onRejectedUrl: 'https://openapi.beisen.com/v2/recruitment/offer/reject-notify',
      callbackAuthType: 'bearer',
      callbackToken: 'beisen_token_771923a',
      retryCount: 3,
      timeoutSec: 8,
    },
    stats: {
      totalCalls: 800,
      successCalls: 800,
      failedCalls: 0,
      lastTriggerTime: '昨天 08:45',
      avgDurationMs: 210,
    },
    createdAt: '2026-06-01',
    updatedAt: '2026-09-23',
  },
];

export const initialIntegrationLogs: IntegrationLogItem[] = [
  {
    id: 'log-001',
    integrationId: 'integ-sap-po',
    integrationName: 'SAP S/4HANA 采购订单与大额付款审批接入',
    systemType: 'ERP',
    externalSn: 'SAP-PO-20260923-4581',
    applicant: '肖主管',
    applicantDept: '市场拓展部',
    targetFormName: '采购付款审批单',
    receivedTime: '15分钟前',
    status: 'processing',
    callbackStatus: 'pending',
    payloadRaw: {
      po_number: 'PO4500098124',
      vendor_name: '创艺会展服务有限公司',
      net_price_cent: 1860000,
      purchasing_group: 'MKT-EAST',
      creator_mail: 'xiao.manager@company.com',
      document_date: '2026-09-23',
      line_items: [
        { item: 10, material: '展位搭建物料包', qty: 5, unit_price: 3720 }
      ]
    },
    resultMessage: 'Webhook 验签通过，成功生成表单实例并触发“多级财务与预算会签流”，当前节点：部门主管审批。',
    durationMs: 312,
  },
  {
    id: 'log-002',
    integrationId: 'integ-feishu-hr',
    integrationName: '飞书人事 People - 员工假勤异常打卡补签接入',
    externalSn: 'FS-ATT-20260923-8819',
    systemType: 'HRM',
    applicant: '周专员',
    applicantDept: '交付实施部',
    targetFormName: '异常考勤申报表',
    receivedTime: '42分钟前',
    status: 'approved',
    callbackStatus: 'success',
    payloadRaw: {
      employee_open_id: 'ou_8a129038ba71203',
      employee_name: '周专员',
      abnormal_date: '2026-09-23',
      exception_reason: '赴苏州交付现场驻场两日，因现场客户内网屏蔽无法连线飞书正常打卡，已提供现场打卡照片。',
      attachment_url: 'https://cdn.feishu.cn/attendance/proof/20260923_suzhou.png'
    },
    resultMessage: '审批终审完成，已将“打卡补卡正常”状态成功回写至飞书人事开放平台，耗时 165ms。',
    durationMs: 165,
  },
  {
    id: 'log-003',
    integrationId: 'integ-fx-crm',
    integrationName: '纷享销客 CRM - 重点商机特批商务折扣申请',
    systemType: 'CRM',
    externalSn: 'CRM-OPP-99210-A',
    applicant: '王经理',
    applicantDept: '大客户部',
    targetFormName: '特批商务折扣申请',
    receivedTime: '2小时前',
    status: 'approved',
    callbackStatus: 'success',
    payloadRaw: {
      opportunity_id: 'OPP-2026-SH-0912',
      customer_name: '华东数智科技有限公司',
      contract_total_amount: 580000,
      proposed_discount: 0.82,
      sales_rep_name: '王经理',
      reason: '战略年度集采框架协议，申请破底折扣以确保排他性合作。'
    },
    resultMessage: '审批流程完成，已向 CRM 回写特批折扣通过指令并解除商机折扣锁定。',
    durationMs: 238,
  },
  {
    id: 'log-004',
    integrationId: 'integ-mall-refund',
    integrationName: '自研电商中台 - 售后大额退款特批表单接入',
    systemType: 'CUSTOM',
    externalSn: 'REFUND-20260923-00129',
    applicant: '系统自动上报',
    applicantDept: '电商交易中台',
    targetFormName: '差旅预支申请单',
    receivedTime: '3小时前',
    status: 'rejected',
    callbackStatus: 'success',
    payloadRaw: {
      refund_sn: 'RF99023812039',
      order_sn: 'OD202609180029',
      refund_fee_yuan: 6800,
      user_uid: 'UID_9921471',
      reject_reason: '退货物流核验未收到对应退件，驳回退款请求。'
    },
    resultMessage: '审批节点做出“驳回”决定，驳回原因已成功回传至自研电商交易中心。',
    durationMs: 295,
  },
  {
    id: 'log-005',
    integrationId: 'integ-sap-po',
    integrationName: 'SAP S/4HANA 采购订单与大额付款审批接入',
    systemType: 'ERP',
    externalSn: 'SAP-PO-20260922-3921',
    applicant: '李专员',
    applicantDept: '基础架构组',
    targetFormName: '采购付款审批单',
    receivedTime: '昨天 16:30',
    status: 'approved',
    callbackStatus: 'success',
    payloadRaw: {
      po_number: 'PO4500098001',
      vendor_name: '天翼云科技有限公司',
      net_price_cent: 4500000,
      purchasing_group: 'IT-INFRA',
      creator_mail: 'li.infra@company.com',
      document_date: '2026-09-22'
    },
    resultMessage: '审批通过，已调用 SAP BAPI 更新采购订单状态为 Released (已放行)。',
    durationMs: 330,
  }
];
