import {
  ProcessConfigModel,
  ProcessTemplate,
  ProcessInstance,
  ProcessAlert,
} from './types';

export const initialProcessConfigs: ProcessConfigModel[] = [
  {
    id: 'cfg-sap-po',
    name: 'SAP S/4HANA 采购单与付款审批对接配置',
    code: 'CONFIG_SAP_PO_V2',
    systemName: 'SAP S/4HANA ERP',
    formName: '采购付款审批单',
    workflowTemplateId: 'tmpl-po-multistage',
    status: 'active',
    version: '2.4.0',
    updatedAt: '2026-09-23 18:40',
    callbackUrl: 'https://erp.enterprise-cloud.cn/bapi/po/status-sync',
    description: '映射 SAP 采购组及物料凭证行项目，转换分到元，并在审批流各节点对财务成本中心分配只读与复核权限。',
    fields: [
      {
        id: 'f-101',
        sourceKey: 'po_number',
        sourceLabel: '采购凭证编号',
        sourceSystem: 'SAP S/4HANA ERP',
        dataType: 'string',
        targetVariable: 'flow.po_number',
        targetComponent: '单行文本 (只读索引)',
        isRequired: true,
        transformRule: 'none',
        sampleValue: 'PO4500098124',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
        description: 'SAP ERP 系统全局唯一采购订单编码',
      },
      {
        id: 'f-102',
        sourceKey: 'vendor_name',
        sourceLabel: '供应商企业全称',
        sourceSystem: 'SAP S/4HANA ERP',
        dataType: 'string',
        targetVariable: 'flow.vendor_name',
        targetComponent: '单行文本 (供应商名称)',
        isRequired: true,
        transformRule: 'none',
        sampleValue: '创艺会展服务有限公司',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
        description: '收款单位公账名称',
      },
      {
        id: 'f-103',
        sourceKey: 'net_price_cent',
        sourceLabel: '订单净额(单位:分)',
        sourceSystem: 'SAP S/4HANA ERP',
        dataType: 'number',
        targetVariable: 'flow.total_amount_yuan',
        targetComponent: '金额大写及数字框',
        isRequired: true,
        transformRule: 'cent_to_yuan',
        sampleValue: '1860000',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'edit',
          finalLeaderNode: 'read',
        },
        description: '将第三方分单位自动转换为元，用于流程条件分支判断',
      },
      {
        id: 'f-104',
        sourceKey: 'purchasing_group',
        sourceLabel: '采购组编码/归属部门',
        sourceSystem: 'SAP S/4HANA ERP',
        dataType: 'string',
        targetVariable: 'flow.dept_code',
        targetComponent: '部门选择器',
        isRequired: true,
        transformRule: 'dept_mapping',
        sampleValue: 'MKT-EAST',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
        description: '映射至本系统组织架构节点',
      },
      {
        id: 'f-105',
        sourceKey: 'creator_mail',
        sourceLabel: '创建人工号/邮箱',
        sourceSystem: 'SAP S/4HANA ERP',
        dataType: 'string',
        targetVariable: 'flow.initiator_account',
        targetComponent: '人员工号',
        isRequired: true,
        transformRule: 'none',
        sampleValue: 'xiao.manager@company.com',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
        description: '流程发起人身份标识',
      },
      {
        id: 'f-106',
        sourceKey: 'tax_code',
        sourceLabel: '增值税税码与税率',
        sourceSystem: 'SAP S/4HANA ERP',
        dataType: 'string',
        targetVariable: 'flow.tax_rate',
        targetComponent: '下拉选择',
        isRequired: false,
        transformRule: 'none',
        sampleValue: 'J1 (6%增值税专用发票)',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'edit',
          finalLeaderNode: 'read',
        },
        description: '财务核算税目分类，财务节点可补充修正',
      },
      {
        id: 'f-107',
        sourceKey: 'cost_center',
        sourceLabel: '成本中心编码',
        sourceSystem: 'SAP S/4HANA ERP',
        dataType: 'string',
        targetVariable: 'flow.cost_center_id',
        targetComponent: '成本中心选择器',
        isRequired: true,
        transformRule: 'none',
        sampleValue: 'CC-901102-MKT',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'edit',
          finalLeaderNode: 'read',
        },
        description: '预算扣减成本中心',
      },
    ],
  },
  {
    id: 'cfg-crm-discount',
    name: '纷享销客 CRM 商机特批折扣字段对接配置',
    code: 'CONFIG_CRM_DISCOUNT_V1',
    systemName: '纷享销客 CRM',
    formName: '特批商务折扣申请',
    workflowTemplateId: 'tmpl-crm-discount',
    status: 'active',
    version: '1.2.0',
    updatedAt: '2026-09-22 14:15',
    callbackUrl: 'https://crm.fxiaoke.com/openapi/v2/discount/sync',
    description: '接入纷享销客商机大单折扣信息，对签约额及申请折扣率进行双重校验并配置销售总监与法务权限。',
    fields: [
      {
        id: 'f-201',
        sourceKey: 'opportunity_id',
        sourceLabel: 'CRM商机唯一编号',
        sourceSystem: '纷享销客 CRM',
        dataType: 'string',
        targetVariable: 'flow.opp_id',
        targetComponent: '单行文本',
        isRequired: true,
        transformRule: 'none',
        sampleValue: 'OPP-2026-SH-0912',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
      {
        id: 'f-202',
        sourceKey: 'customer_name',
        sourceLabel: '客户企业名称',
        sourceSystem: '纷享销客 CRM',
        dataType: 'string',
        targetVariable: 'flow.customer_name',
        targetComponent: '单行文本',
        isRequired: true,
        transformRule: 'none',
        sampleValue: '华东数智科技有限公司',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
      {
        id: 'f-203',
        sourceKey: 'contract_total_amount',
        sourceLabel: '合同总预算(元)',
        sourceSystem: '纷享销客 CRM',
        dataType: 'number',
        targetVariable: 'flow.contract_amount',
        targetComponent: '金额框',
        isRequired: true,
        transformRule: 'none',
        sampleValue: '580000',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
      {
        id: 'f-204',
        sourceKey: 'proposed_discount',
        sourceLabel: '申请折扣率',
        sourceSystem: '纷享销客 CRM',
        dataType: 'number',
        targetVariable: 'flow.discount_rate',
        targetComponent: '百分比框',
        isRequired: true,
        transformRule: 'none',
        sampleValue: '0.82',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
    ],
  },
  {
    id: 'cfg-feishu-hr',
    name: '飞书人事打卡补签异常接入字段配置',
    code: 'CONFIG_FEISHU_ATTENDANCE_V3',
    systemName: '飞书人事 (Feishu)',
    formName: '异常考勤申报表',
    workflowTemplateId: 'tmpl-hr-attendance',
    status: 'active',
    version: '3.1.0',
    updatedAt: '2026-09-23 11:30',
    callbackUrl: 'https://open.feishu.cn/open-apis/attendance/v1/user_approvals/sync',
    description: '通过飞书事件总线获取打卡异常时间戳，自动解析异常类型与考勤组，终审通过后调用飞书 OpenAPI 写回。',
    fields: [
      {
        id: 'f-301',
        sourceKey: 'employee_open_id',
        sourceLabel: '飞书人员 OpenID',
        sourceSystem: '飞书人事 (Feishu)',
        dataType: 'string',
        targetVariable: 'flow.feishu_open_id',
        targetComponent: '隐藏系统字段',
        isRequired: true,
        transformRule: 'none',
        sampleValue: 'ou_8a129038ba71203',
        nodePermissions: {
          startNode: 'read',
          deptManagerNode: 'hide',
          financeAuditNode: 'hide',
          finalLeaderNode: 'hide',
        },
      },
      {
        id: 'f-302',
        sourceKey: 'employee_name',
        sourceLabel: '员工姓名/花名',
        sourceSystem: '飞书人事 (Feishu)',
        dataType: 'string',
        targetVariable: 'flow.staff_name',
        targetComponent: '单行文本',
        isRequired: true,
        transformRule: 'none',
        sampleValue: '周专员',
        nodePermissions: {
          startNode: 'read',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
      {
        id: 'f-303',
        sourceKey: 'abnormal_date',
        sourceLabel: '打卡异常日期',
        sourceSystem: '飞书人事 (Feishu)',
        dataType: 'date',
        targetVariable: 'flow.abnormal_date',
        targetComponent: '日期选择器',
        isRequired: true,
        transformRule: 'date_format',
        sampleValue: '2026-09-23',
        nodePermissions: {
          startNode: 'read',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
      {
        id: 'f-304',
        sourceKey: 'exception_reason',
        sourceLabel: '假勤异常原由详述',
        sourceSystem: '飞书人事 (Feishu)',
        dataType: 'string',
        targetVariable: 'flow.reason',
        targetComponent: '多行文本',
        isRequired: true,
        transformRule: 'none',
        sampleValue: '赴苏州交付现场驻场两日，因内网屏蔽无法连线飞书打卡。',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
    ],
  },
  {
    id: 'cfg-mall-refund',
    name: '自研电商中台大额退款对接字段配置',
    code: 'CONFIG_MALL_REFUND_V1',
    systemName: '自研电商业务中台',
    formName: '大额退款特批表单',
    workflowTemplateId: 'tmpl-refund-risk',
    status: 'active',
    version: '1.0.1',
    updatedAt: '2026-09-21 16:50',
    callbackUrl: 'https://trade-api.internal-mall.com/order/refund/action-approve',
    description: '自研业务中台微服务大额退款审核，包含逆向物流单号、会员UID与退汇渠道验证。',
    fields: [
      {
        id: 'f-401',
        sourceKey: 'refund_sn',
        sourceLabel: '售后退款流水单号',
        sourceSystem: '自研电商业务中台',
        dataType: 'string',
        targetVariable: 'flow.refund_sn',
        targetComponent: '单行文本',
        isRequired: true,
        transformRule: 'none',
        sampleValue: 'RF99023812039',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
      {
        id: 'f-402',
        sourceKey: 'refund_fee_yuan',
        sourceLabel: '退款申请金额(元)',
        sourceSystem: '自研电商业务中台',
        dataType: 'number',
        targetVariable: 'flow.refund_fee',
        targetComponent: '金额框',
        isRequired: true,
        transformRule: 'none',
        sampleValue: '6800',
        nodePermissions: {
          startNode: 'edit',
          deptManagerNode: 'read',
          financeAuditNode: 'read',
          finalLeaderNode: 'read',
        },
      },
    ],
  },
];

export const initialProcessTemplates: ProcessTemplate[] = [
  {
    id: 'tmpl-po-multistage',
    name: '采购与付款多级智能分流审批流',
    code: 'TMPL_PO_FINANCE_APPROVAL',
    category: '采购财务',
    description: '面向 SAP / 用友 ERP 的大额采购支出。金额小于 5 万元由直属主管及财务审核；大于 5 万元自动分支流转至业务副总裁与财务总监终审。',
    boundSystem: 'SAP S/4HANA ERP',
    triggerType: 'webhook_api',
    version: 'v2.6',
    status: 'active',
    instanceCount: 1420,
    avgDuration: '2.8 小时',
    updatedAt: '2026-09-23 15:30',
    nodes: [
      { id: 'n1', name: '第三方SAP报文接入', type: 'start' },
      { id: 'n2', name: '部门主管初审', type: 'approver', assigneeType: 'supervisor', assigneeName: '申请人直属主管', approvalMode: 'or', timeoutHours: 12 },
      { id: 'n3', name: '金额分支条件', type: 'condition', conditionExpr: 'flow.total_amount_yuan >= 50000' },
      { id: 'n4', name: '财务合规与预算核准', type: 'approver', assigneeType: 'role', assigneeName: '高级财务分析师 (会签)', approvalMode: 'and', timeoutHours: 24 },
      { id: 'n5', name: '分管VP与CFO审批', type: 'approver', assigneeType: 'role', assigneeName: '业务VP / 财务总监 (大额特批)', approvalMode: 'sequential', timeoutHours: 48 },
      { id: 'n6', name: '回写SAP ERP状态 (Released)', type: 'callback', actionUrl: 'https://erp.enterprise-cloud.cn/bapi/po/release' },
      { id: 'n7', name: '流程办结', type: 'end' },
    ],
  },
  {
    id: 'tmpl-crm-discount',
    name: '大客户商业折扣委员会特批流',
    code: 'TMPL_CRM_DISCOUNT_CONTROL',
    category: '营销特批',
    description: '对接 CRM 商机系统，当折扣低于 85 折或合同额超 100 万元时自动触发跨部门商业风控合规审定。',
    boundSystem: '纷享销客 CRM',
    triggerType: 'webhook_api',
    version: 'v1.4',
    status: 'active',
    instanceCount: 860,
    avgDuration: '1.6 小时',
    updatedAt: '2026-09-22 18:20',
    nodes: [
      { id: 'n11', name: 'CRM商机特批接入', type: 'start' },
      { id: 'n12', name: '销售区域总监审批', type: 'approver', assigneeType: 'supervisor', assigneeName: '大区销售总监', approvalMode: 'or', timeoutHours: 8 },
      { id: 'n13', name: '法务与价格风控部会签', type: 'approver', assigneeType: 'role', assigneeName: '商业风控委员会 (会签)', approvalMode: 'and', timeoutHours: 12 },
      { id: 'n14', name: '回写CRM解除折扣锁定', type: 'callback', actionUrl: 'https://crm.fxiaoke.com/openapi/v2/discount/sync' },
      { id: 'n15', name: '抄送大客户交付部', type: 'cc', assigneeName: '实施交付组' },
      { id: 'n16', name: '流程办结', type: 'end' },
    ],
  },
  {
    id: 'tmpl-hr-attendance',
    name: '考勤假勤异常与直属领导确认流',
    code: 'TMPL_HR_ATTENDANCE_OVERRIDE',
    category: '行政人事',
    description: '通过飞书/北森开放事件订阅打卡异常，直属主管审批通过后自动调用第三方接口补卡并更新排班。',
    boundSystem: '飞书人事 (Feishu)',
    triggerType: 'webhook_api',
    version: 'v3.0',
    status: 'active',
    instanceCount: 3200,
    avgDuration: '0.8 小时',
    updatedAt: '2026-09-23 10:15',
    nodes: [
      { id: 'n21', name: '飞书异常考勤接入', type: 'start' },
      { id: 'n22', name: '直属领导审批', type: 'approver', assigneeType: 'supervisor', assigneeName: '直属部门Leader', approvalMode: 'or', timeoutHours: 24 },
      { id: 'n23', name: '人事考勤专员复核', type: 'approver', assigneeType: 'role', assigneeName: 'HR假勤专员', approvalMode: 'or', timeoutHours: 24 },
      { id: 'n24', name: '飞书考勤写回接口', type: 'callback' },
      { id: 'n25', name: '流程结束', type: 'end' },
    ],
  },
  {
    id: 'tmpl-refund-risk',
    name: '自研电商大额逆向退款风控联审流',
    code: 'TMPL_MALL_HIGH_REFUND',
    category: '自研中台',
    description: '单笔大于 5,000 元退货退款自动化联审，集成仓库验货状态检测与财务出纳原路退汇驱动。',
    boundSystem: '自研电商业务中台',
    triggerType: 'webhook_api',
    version: 'v1.2',
    status: 'active',
    instanceCount: 940,
    avgDuration: '1.2 小时',
    updatedAt: '2026-09-21 20:00',
    nodes: [
      { id: 'n31', name: '中台退款事件触发', type: 'start' },
      { id: 'n32', name: '客服风控专员核验', type: 'approver', assigneeType: 'role', assigneeName: '售后风控专员', approvalMode: 'or', timeoutHours: 4 },
      { id: 'n33', name: '仓储质检确认 (WMS)', type: 'approver', assigneeType: 'role', assigneeName: '仓储验货主管', approvalMode: 'or', timeoutHours: 6 },
      { id: 'n34', name: '支付渠道原路退回驱动', type: 'callback' },
      { id: 'n35', name: '结束', type: 'end' },
    ],
  },
];

export const initialProcessInstances: ProcessInstance[] = [
  {
    id: 'inst-001',
    instanceSn: 'PROC-20260923-0098',
    externalSn: 'SAP-PO-4500098124',
    processName: 'SAP S/4HANA 采购单与付款审批对接配置',
    templateCode: 'TMPL_PO_FINANCE_APPROVAL',
    sourceSystem: 'SAP S/4HANA ERP',
    initiator: '肖主管 (市场部)',
    initiatorDept: '市场拓展中心 - 华东分部',
    startTime: '2026-09-23 16:15',
    duration: '2小时25分',
    status: 'running',
    currentNodeName: '财务合规与预算核准 (会签中)',
    currentAssignees: ['张财务 (高级分析师)', '李审计 (风控部)'],
    priority: 'high',
    callbackStatus: 'pending',
    businessData: {
      '采购凭证编号': 'PO4500098124',
      '供应商全称': '创艺会展服务有限公司',
      '申报金额': '¥ 186,000.00 元',
      '采购组编码': 'MKT-EAST',
      '创建人邮箱': 'xiao.manager@company.com',
      '成本中心': 'CC-901102-MKT',
      '付款方式': '对公电汇 (预付30%)',
    },
    approvalLogs: [
      {
        nodeName: '第三方SAP报文接入',
        operator: 'SAP Webhook Gateway',
        role: '系统自动上报',
        action: 'submit',
        comment: 'SAP 系统单据创建成功，Webhook 报文验签通过并自动生成流程实例。',
        timestamp: '2026-09-23 16:15:02',
      },
      {
        nodeName: '部门主管初审',
        operator: '王总监',
        role: '市场部负责人',
        action: 'approve',
        comment: '秋季全球展位搭建物料已纳入 Q3 预算规划，审核通过，准予进入财务会签环节。',
        timestamp: '2026-09-23 17:02:18',
      },
      {
        nodeName: '财务合规与预算核准',
        operator: '张财务',
        role: '高级财务分析师',
        action: 'pending',
        comment: '正在核对 SAP 内部成本中心 CC-901102 预算剩余额度及开票抬头合规性...',
        timestamp: '2026-09-23 17:02:19',
      },
    ],
  },
  {
    id: 'inst-002',
    instanceSn: 'PROC-20260923-0092',
    externalSn: 'FS-ATT-20260923-8819',
    processName: '飞书人事打卡补签异常接入字段配置',
    templateCode: 'TMPL_HR_ATTENDANCE_OVERRIDE',
    sourceSystem: '飞书人事 (Feishu)',
    initiator: '周专员',
    initiatorDept: '交付实施部 - 华东战队',
    startTime: '2026-09-23 14:10',
    duration: '48分钟',
    status: 'approved',
    currentNodeName: '流程已归档办结 (已回写飞书)',
    currentAssignees: ['-'],
    priority: 'normal',
    callbackStatus: 'success',
    businessData: {
      '员工姓名': '周专员 (00812)',
      '打卡异常日期': '2026-09-23',
      '补卡理由': '赴苏州交付现场驻场两日，因内网屏蔽无法连线飞书正常打卡。',
      '直属领导': '赵组长',
      '回写状态': '飞书打卡记录已修正为“正常”',
    },
    approvalLogs: [
      {
        nodeName: '飞书异常考勤接入',
        operator: 'Feishu Open Event',
        role: '开放平台接入',
        action: 'submit',
        comment: '接收到员工在移动端飞书打卡异常补签申报请求。',
        timestamp: '2026-09-23 14:10:05',
      },
      {
        nodeName: '直属领导审批',
        operator: '赵组长',
        role: '实施组长',
        action: 'approve',
        comment: '属实，周专员确实在苏州客户现场调试内网服务器。同意补卡。',
        timestamp: '2026-09-23 14:35:10',
      },
      {
        nodeName: '人事考勤专员复核',
        operator: '钱人事',
        role: '考勤主管',
        action: 'approve',
        comment: '核对工单凭证无误，予以准假。',
        timestamp: '2026-09-23 14:58:20',
      },
      {
        nodeName: '飞书考勤写回接口',
        operator: 'System OpenAPI Sync',
        role: '系统回调',
        action: 'approve',
        comment: '成功调用 Feishu attendance/v1/user_approvals/sync 回写打卡结果 (HTTP 200 OK)。',
        timestamp: '2026-09-23 14:58:22',
      },
    ],
  },
  {
    id: 'inst-003',
    instanceSn: 'PROC-20260923-0087',
    externalSn: 'CRM-OPP-99210-A',
    processName: '纷享销客 CRM 商机特批折扣字段对接配置',
    templateCode: 'TMPL_CRM_DISCOUNT_CONTROL',
    sourceSystem: '纷享销客 CRM',
    initiator: '王经理 (大客户部)',
    initiatorDept: '大客户战略销售一组',
    startTime: '2026-09-23 10:20',
    duration: '1小时40分',
    status: 'approved',
    currentNodeName: '流程已归档办结 (已回写CRM)',
    currentAssignees: ['-'],
    priority: 'urgent',
    callbackStatus: 'success',
    businessData: {
      '商机编号': 'OPP-2026-SH-0912',
      '客户企业': '华东数智科技有限公司',
      '预计签约额': '¥ 580,000.00 元',
      '申请特批折扣': '8.2 折 (0.82)',
      '基准底线折扣': '8.8 折 (破底0.06)',
      '申报销售': '王经理',
    },
    approvalLogs: [
      {
        nodeName: 'CRM商机特批接入',
        operator: 'CRM Open API',
        role: '系统触发',
        action: 'submit',
        comment: '商机阶段推进至特批评审，锁定 CRM 报价单。',
        timestamp: '2026-09-23 10:20:00',
      },
      {
        nodeName: '销售区域总监审批',
        operator: '孙总监',
        role: '大区销售总监',
        action: 'approve',
        comment: '战略标杆年度集采客户，认可破底折扣以确保 100% 签约胜率。',
        timestamp: '2026-09-23 11:10:45',
      },
      {
        nodeName: '法务与价格风控部会签',
        operator: '陈法务 / 周风控',
        role: '风控委员会',
        action: 'approve',
        comment: '已追加排他性付款协议及分期履约保障条款，合规性审查通过。',
        timestamp: '2026-09-23 12:00:15',
      },
      {
        nodeName: '回写CRM解除折扣锁定',
        operator: 'CRM Callback Service',
        role: '系统回调',
        action: 'approve',
        comment: '已同步特批折扣 0.82 至 CRM 并更新商机赢率。',
        timestamp: '2026-09-23 12:00:18',
      },
    ],
  },
  {
    id: 'inst-004',
    instanceSn: 'PROC-20260923-0075',
    externalSn: 'REFUND-20260923-00129',
    processName: '自研电商中台大额退款对接字段配置',
    templateCode: 'TMPL_MALL_HIGH_REFUND',
    sourceSystem: '自研电商业务中台',
    initiator: '电商微服务系统',
    initiatorDept: '交易风控中台',
    startTime: '2026-09-23 09:15',
    duration: '25分钟',
    status: 'rejected',
    currentNodeName: '审批已被驳回 (已回写业务端)',
    currentAssignees: ['-'],
    priority: 'high',
    callbackStatus: 'success',
    businessData: {
      '退款单号': 'RF99023812039',
      '关联合同': 'OD202609180029',
      '申请退款额': '¥ 6,800.00 元',
      '驳回原由': '退货物流拆包核验未收到关键核心配件，判定不符合全额退款条件。',
    },
    approvalLogs: [
      {
        nodeName: '中台退款事件触发',
        operator: 'Trade Engine Service',
        role: '系统消息队列',
        action: 'submit',
        comment: '买家端触发 6,800 元售后退款，达到 5,000 元特批阀值，上报审批。',
        timestamp: '2026-09-23 09:15:10',
      },
      {
        nodeName: '客服风控专员核验',
        operator: '吴风控',
        role: '风控专员',
        action: 'approve',
        comment: '初审通过，转由仓储质检人员确认实物退货入库状态。',
        timestamp: '2026-09-23 09:25:30',
      },
      {
        nodeName: '仓储质检确认 (WMS)',
        operator: '刘主管',
        role: '仓储质检主管',
        action: 'reject',
        comment: '实物拆包核验发现包装箱内缺失主机原装电源适配器及保修卡，予以驳回！',
        timestamp: '2026-09-23 09:40:02',
      },
      {
        nodeName: '结果回写中台',
        operator: 'Trade API Callback',
        role: '系统回调',
        action: 'reject',
        comment: '驳回原因已成功回写至交易中台，买家退款单状态变更为“已拒绝”。',
        timestamp: '2026-09-23 09:40:05',
      },
    ],
  },
  {
    id: 'inst-005',
    instanceSn: 'PROC-20260923-0062',
    externalSn: 'SAP-PO-4500098001',
    processName: 'SAP S/4HANA 采购单与付款审批对接配置',
    templateCode: 'TMPL_PO_FINANCE_APPROVAL',
    sourceSystem: 'SAP S/4HANA ERP',
    initiator: '李专员 (基础架构组)',
    initiatorDept: '技术研发中心 - 云计算运维部',
    startTime: '2026-09-22 15:40',
    duration: '4小时12分',
    status: 'approved',
    currentNodeName: '流程已归档办结 (SAP已放行)',
    currentAssignees: ['-'],
    priority: 'normal',
    callbackStatus: 'success',
    businessData: {
      '采购凭证编号': 'PO4500098001',
      '供应商全称': '天翼云科技有限公司',
      '申报金额': '¥ 45,000.00 元',
      '成本中心': 'CC-IT-INFRA-01',
      '采购组编码': 'IT-INFRA',
    },
    approvalLogs: [
      {
        nodeName: '第三方SAP报文接入',
        operator: 'SAP Webhook Gateway',
        role: '系统触发',
        action: 'submit',
        comment: '算力节点续费采购单接入。',
        timestamp: '2026-09-22 15:40:00',
      },
      {
        nodeName: '部门主管初审',
        operator: '宋总监',
        role: '研发总监',
        action: 'approve',
        comment: '基础设施刚性扩容，同意。',
        timestamp: '2026-09-22 16:30:12',
      },
      {
        nodeName: '财务合规与预算核准',
        operator: '张财务',
        role: '高级财务分析师',
        action: 'approve',
        comment: '核对云资源预算台账充盈，核准通过。',
        timestamp: '2026-09-22 19:52:10',
      },
    ],
  },
];

export const initialProcessAlerts: ProcessAlert[] = [
  {
    id: 'alert-01',
    level: 'warning',
    title: '审批节点超时预警 (停留超 18 小时)',
    message: '实例 PROC-20260923-0098 在节点【财务合规与预算核准】已停留 18 小时，逼近 24 小时 SLA 阈值，已触发催办提醒。',
    sourceSystem: 'SAP S/4HANA ERP',
    time: '20分钟前',
    resolved: false,
    relatedInstanceSn: 'PROC-20260923-0098',
  },
  {
    id: 'alert-02',
    level: 'info',
    title: '第三方回调重试成功',
    message: '飞书考勤写回接口因瞬间网络抖动首次返回 HTTP 504，系统在 30 秒后自动重试成功并写回打卡结果。',
    sourceSystem: '飞书人事 (Feishu)',
    time: '1小时前',
    resolved: true,
    relatedInstanceSn: 'PROC-20260923-0092',
  },
  {
    id: 'alert-03',
    level: 'warning',
    title: '外部报文缺少非必填扩展字段 (建议核实)',
    message: '纷享销客 CRM 推送商机报文中未携带 [tax_identification_number] 字段，已使用默认值兜底解析。',
    sourceSystem: '纷享销客 CRM',
    time: '3小时前',
    resolved: true,
    relatedInstanceSn: 'PROC-20260923-0087',
  },
];

export const monitorOverviewMetrics = {
  activeInstances: 48,
  todayCompleted: 136,
  avgApprovalHours: '1.9h',
  slaComplianceRate: '98.6%',
  callbackSuccessRate: '99.9%',
  slowestNodes: [
    { nodeName: '财务合规与预算核准', processName: 'SAP采购与付款审批流', avgHours: 3.4, pendingCount: 14, manager: '张财务 / 财务风控组' },
    { nodeName: '法务与价格风控部会签', processName: 'CRM商机特批折扣流', avgHours: 2.1, pendingCount: 6, manager: '陈法务 / 商业风控委员会' },
    { nodeName: '分管VP与CFO终审', processName: '大额支出特批流', avgHours: 4.8, pendingCount: 3, manager: '业务VP' },
    { nodeName: '仓储质检核验 (WMS)', processName: '电商大额退款风控联审流', avgHours: 1.5, pendingCount: 5, manager: '刘主管 / 仓储部' },
  ],
  trend7Days: [
    { date: '09-17', triggered: 84, completed: 82 },
    { date: '09-18', triggered: 92, completed: 89 },
    { date: '09-19', triggered: 110, completed: 106 },
    { date: '09-20', triggered: 125, completed: 120 },
    { date: '09-21', triggered: 118, completed: 115 },
    { date: '09-22', triggered: 142, completed: 139 },
    { date: '09-23', triggered: 156, completed: 148 },
  ],
};
